### ISSUE TITLE
Trade withdraw asset_id

### ISSUE THREAD

**Issue by ckypper** [OfficialCSGOEmpire/API-Docs#5]
Hi guys, 
I want to get asset_id when i withdraw an item
Can u guys add it in websocket event trade_status withdrawal

**Comment by Art-em1s** [comment]
You can just request your steam inventory and get it that way.

Asset ids aren't a defining factor for trades via empire, they also change upon being traded, so we'd have to get the withdrawing users inventory in order to do so, which is a relatively unnecessary process.

**Comment by ckypper** [comment]
but if i'm the depositer i got asset_id from trade_status deposit event when someone withdraw my item. so why u guy can send asset_id to depositer but not withdrawer

**Comment by Art-em1s** [comment]
In order to know what items you have in your inventory we have to load your inventory. Inventories are only updated once per hour, to reduce the spam requests against steams api.

As I said, you can just get your own inventory after the trade completes and look for the newest asset id

**Comment by ckypper** [comment]
I only want to say that why u guys can send asset_id to the depositer when a trade happened but not the withdrawer.
Cause if i look up my own inventory, there're some case that is not correct, like multiple new item with the same name in steam inventory at the same time.

**Comment by ckypper** [comment]
42 / trade, ["trade_status", {
    "type": "deposit",
    "data": {
        "id": 10002,
        "user_id": 303119,
        "items": [{
            "app_id": 730,
            "appid": 730,
            "asset_id": "5628460986",
            "assetid": "5628460986",
            "context_id": "2",
            "contextid": "2",
            "description_type": "Remarkable Sticker",
            "icon_url": "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRcWEDRSfCshZ-CBBJiNTtfubaqZQQ1gKGdJjwRvIjjxdOJxvP3Me3SzzMJuJwiiL6S9Irz2QfjrUVlamjtZNjCQh4JqWM",
            "id": "5628460986",
            "img": "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRcWEDRSfCshZ-CBBJiNTtfubaqZQQ1gKGdJjwRvIjjxdOJxvP3Me3SzzMJuJwiiL6S9Irz2QfjrUVlamjtZNjCQh4JqWM",
            "inspect_key": 2335751007372407000,
            "is_commodity": true,
            "market_name": "Sticker | Virtus.Pro (Holo) | Atlanta 2017",
            "market_value": 45.55,
            "name": "Sticker | Virtus.Pro (Holo) | Atlanta 2017",
            "name_color": "D2D2D2",
            "paint_index": null,
            "preview_id": null,
            "price_is_unreliable": 0,
            "raw_price": 3190,
            "tradable": true,
            "tradelock": false,
            "type": "users",
            "updated_at": "2021-09-10 06:49:35",
            "wear": null
        }],
        "total_value": 4555,
        "tradeoffer_id": 10002,
        "status": 4,
        "status_message": "Confirming",
        "metadata": {
            "auction_item_id": "1aruaja",
            "auction_highest_bid": 4555,
            "auction_highest_bidder": 4900627,
            "auction_number_of_bids": 1,
            "auction_ends_at": 1631266352,
            "auction_auto_withdraw_failed": null,
            "timestamp": null,
            "price_updated_at": null,
            "trade_url": null,
            "bot": null,
            "total_fee": null,
            "fee": null,
            "old_total_value": null,
            "pending_withdrawal_id": null,
            "item_position_in_inventory": null,
            "item_inspected": null,
            "steam_id": "76561198106192114",
            "phishingScamDetected": null,
            "item_validation": null,
            "possible_abuse_detected_at": null,
            "penalty": null
        },
        "created_at": "2021-09-10 09:32:14",
        "updated_at": "2021-09-10 09:32:33"
    }
}]
This is message was sent to the depositer
I'm asking u guys to send it to the withdrawer as well :(

**Comment by Art-em1s** [comment]
As I said, the best way for you to achieve this would be to get the newest asset id from your inventory.

Locked for spam.
