### ISSUE TITLE
Failing to deposit item

### ISSUE THREAD

**Issue by sayanlp99** [OfficialCSGOEmpire/API-Docs#7]
![Screenshot 2022-07-24 195424](https://user-images.githubusercontent.com/28763093/180651566-926d7f01-8bf0-4e04-be98-e8ff30baf7f2.png)

The response says that items is missing, but I have added items in the body

**Comment by Art-em1s** [comment]
Hi, make sure you're declaring the content you're sending as JSON via headers.

```
'Content-Type': 'application/json'
```
